// // Copyright 2023 Jan Erik Schopmeier (@janschop)
// // SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

/*
 * Feature disable options
 *  These options are also useful to firmware size reduction.
 */
// #define SERIAL_PIO_USE_PIO1
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

#define DYNAMIC_MACRO_DELAY 50
#define COMBO_ONLY_FROM_LAYER 6
#define TAPPING_TOGGLE 3
#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 600
#define PERMISSIVE_HOLD_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define TAPPING_TERM 200
#define COMBO_TERM 60

// // only for right side
// // #define I2C_DRIVER I2CD1
// // #define I2C_SDA_PIN GP2
// // #define I2C_SCL_PIN GP3

// // #define SPLIT_USB_DETECT

// #define AZOTEQ_IQS5XX_TPS65
// #define AZOTEQ_IQS5XX_TWO_FINGER_TAP_ENABLE true
// #define AZOTEQ_IQS5XX_ZOOM_ENABLE false
// #define AZOTEQ IQS5XX_SCROLL_ENABLE false
// // #define AZOTEQ_IQS5XX_ROTATION_90
// #define AZOTEQ_IQS5XX_PRESS_AND_HOLD_ENABLE false
// #define AZOTEQ_IQS5XX_SWIPE_X_ENABLE true
// #define AZOTEQ_IQS5XX_SWIPE_Y_ENABLE true
// #define AZOTEQ_IQS5XX_TAP_TIME 150
// #define AZOTEQ_IQS5XX_TAP_DISTANCE 10
// //#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE 
// #define POINTING_DEVICE_ROTATION_90
// #define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE true

// Mouse key speed and acceleration.
#define MOUSEKEY_INERTIA
#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY          150
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL       16
#undef MOUSEKEY_MAX_SPEED 
#define MOUSEKEY_MAX_SPEED      40
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX    40
#undef MOUSEKEY_FRICTION
#define MOUSEKEY_FRICTION       13
#undef MOUSEKEY_MOVE_DELTA
#define MOUSEKEY_MOVE_DELTA     2

#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY    180
#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 60
#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 3
#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX 255