VPATH += keyboards/gboards
SERIAL_DRIVER = vendor
COMBO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
# DYNAMIC_TAPPING_TERM_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
# sm_td
DEFERRED_EXEC_ENABLE = yes
