// Copyright 2023 Jan Erik Schopmeier (@janschop)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once


#define SPI_SCK_PIN GP2
#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN GP4
#define POINTING_DEVICE_CS_PIN GP5


#define CIRQUE_PINNACLE_DIAMETER_MM 35
// #define CIRQUE_PINNACLE_ADDR 0x2A
// #define CIRQUE_PINNACLE_TIMEOUT 1000
// #define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_RELATIVE_MODE
// #define CIRQUE_PINNACLE_SKIP_SENSOR_CHECK
// #define CIRQUE_PINNACLE_REACHABLE_CALIBRATION
// #define CIRQUE_PINNACLE_TAP_ENABLE
// #define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
// #define POINTING_DEVICE_GESTURES_SCROLL_ENABLE 
// #define POINTING_DEVICE_ROTATION_90
