// Copyright 2023 Jan Erik Schopmeier (@janschop)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once


// #undef I2C_DRIVER 
// #undef I2C_SDA_PIN
// #undef I2C_SCL_PIN
#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP12
#define I2C1_SCL_PIN GP9


// #define CIRQUE_PINNACLE_DIAMETER_MM 40
// #define CIRQUE_PINNACLE_ADDR 0x2A
// #define CIRQUE_PINNACLE_TIMEOUT 1000
// #define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_RELATIVE_MODE
// #define CIRQUE_PINNACLE_SKIP_SENSOR_CHECK
// #define CIRQUE_PINNACLE_REACHABLE_CALIBRATION
// #define CIRQUE_PINNACLE_TAP_ENABLE
// #define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
// #define POINTING_DEVICE_GESTURES_SCROLL_ENABLE 
// #define POINTING_DEVICE_ROTATION_90
