# This file intentionally left blank

RGBLIGHT_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no
CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = no
TAP_DANCE_ENABLE = yes
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = bitbang
COMBO_ENABLE = yes