# SRC += features/layer_lock.c
# VPATH += keyboards/gboards

CONSOLE_ENABLE = yes
RGBLIGHT_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no
CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = no
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = bitbang
COMBO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes